### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by JaMo42** [bisqwit/dirr#1]
Building fails as std::lock is not defined in `dfa_match.cc`.
Need to add `#include <mutex>`.

**Comment by bisqwit** [comment]
Which platform?

`dfa_match.hh` has these lines:

```
#ifdef __SUNPRO_CC
#define DFA_DISABLE_MUTEX
#endif

#ifndef DFA_DISABLE_MUTEX
#if __cplusplus >= 201402L && !defined(NO_SHARED_TIMED_MUTEX)
# include <shared_mutex>
#else
# include <mutex>   // std::mutex for thread-safety
#endif
#endif
```

And `dfa_match.cc` #includes `dfa_match.hh` before it uses anything `std::lock`.

**Comment by JaMo42** [comment]
I had the problem on every Linux distribution I've used so far (Ubuntu, Mint, Manjaro) and always had to put the extra include into the file. This might a configuration problem on my end, which makes me wonder why it happened on every distro I've used.
